# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push only for the main branch
  push:
    branches:
      - zen_ima_2.13.3
  pull_request:
    branches:
      - zen_ima_2.13.3

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup IP
        run: echo "13.232.78.227 mx.nexus.com" | sudo tee -a /etc/hosts
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Execute unit tests
      - name: Unit-Test
        env:
          MX_NEXUS_USER: ${{ secrets.GIT_READ_USERNAME }}
          MX_NEXUS_PW: ${{ secrets.GIT_READ_PASSWORD }}
        run: ./gradlew :extension-mxInteractiveMediaAds:testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs : test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Initiation notification
        if: always()
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#publish_exo_lib'
          text: 'Job started for "${env.GITHUB_REPOSITORY}" with Run Number: ${env.GITHUB_RUN_NUMBER}. Commit Info: ${env.GITHUB_REF}:${env.GITHUB_SHA} and cause is ${env.GITHUB_EVENT_NAME}. For more details refer to: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}'
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Setup IP
        run: echo "13.232.78.227 mx.nexus.com" | sudo tee -a /etc/hosts
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Runs a set of commands using the runners shell
      - name: Clean
        if: always()
        run: ./gradlew clean
      - name: Assemble
        id: assemble
        if: always()
        env:
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.build_number }}
          publisherUserName: ${{ secrets.MAVEN_USERNAME }}
          publisherPassword: ${{ secrets.MAVEN_PASSWORD }}
          MX_NEXUS_USER: ${{ secrets.GIT_READ_USERNAME }}
          MX_NEXUS_PW: ${{ secrets.GIT_READ_PASSWORD }}
          publishUrlRelease: ${{ secrets.MAVEN_RELEASE_URL }}
          publishVersion: 7.0.0.${{env.BUILD_NUMBER}}
          publishVersionCode: 700
        run: ./gradlew assembleRelease
      - name: Publish
        id: publish
        env:
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.build_number }}
          publisherUserName: ${{ secrets.MAVEN_USERNAME }}
          publisherPassword: ${{ secrets.MAVEN_PASSWORD }}
          MX_NEXUS_USER: ${{ secrets.GIT_READ_USERNAME }}
          MX_NEXUS_PW: ${{ secrets.GIT_READ_PASSWORD }}
          publishUrlRelease: ${{ secrets.MAVEN_RELEASE_URL }}
          publishVersion: 7.0.0.${{env.BUILD_NUMBER}}
          publishVersionCode: 700
        run: ./gradlew publishMavenReleasePublicationToReleaseRepository
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build notification
        if: always()
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.build_number }}
          RELEASE_REF: 7.0.0.${{env.BUILD_NUMBER}}
        with:
          channel: '#publish_exo_lib'
          status: ${{ job.status }}
          success_text: |
            '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) : Successful:
            \ncom.mxplay.code.exo:library-core:${{ env.RELEASE_REF }}
            \ncom.mxplay.code.exo:library-dash:${{ env.RELEASE_REF }}
            \ncom.mxplay.code.exo:library-hls:${{ env.RELEASE_REF }}
            \ncom.mxplay.code.exo:extension-ima:${{ env.RELEASE_REF }}
            \ncom.mxplay.code.exo:extension-mxInteractiveMediaAds:${{ env.RELEASE_REF }}
            \ncom.mxplay.code.exo:extension-dav1d:${{ env.RELEASE_REF }}
            \ncom.mxplay.code.exo:extension-vvc:${{ env.RELEASE_REF }}
            \ncom.mxplay.code.exo:extension-okhttp:${{ env.RELEASE_REF }}'
          failure_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) : Failed'
          cancelled_text: '${env.GITHUB_WORKFLOW} (${env.GITHUB_RUN_NUMBER}) : Cancelled'
          fields: |
            [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": false },
            { "title": "Branch", "value": "${env.GITHUB_REF}", "short": false },
            { "title": "User", "value": "${env.GITHUB_ACTOR}", "short": false },
            { "title": "Commit SHA", "value": "${env.GITHUB_SHA}", "short": false },
            { "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}", "short": false}]

  sync:
    # The type of runner that the job will run on
    needs: build
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Nexus Sync
        id: nexus-sync
        shell: bash
        continue-on-error: true
        run: curl "http://nitinjain:11942112d2643be35dfe0c3217066e6a22@3.34.134.141:8080/job/sync-nexus/build?token=11942112d2643be35dfe0c3217066e6a22"
      - name: Nexus Sync Fallback
        if: ${{steps.nexus-sync.outcome != 'success'}}
        id: nexus-fall
        shell: bash
        continue-on-error: true
        run: curl "http://nitinjain:11942112d2643be35dfe0c3217066e6a22@13.232.78.227:8080/job/sync-nexus/build?token=11942112d2643be35dfe0c3217066e6a22"
      - name: Sync notification
        if: ${{ steps.nexus-sync.outcome != 'success' && steps.nexus-fall.outcome != 'success' }}
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#publish_exo_lib'
          username: 'Batman'
          text:  'Please Manually run Nexus Sync from Jenkins'
          color: 'danger'

